"""Add news table

Revision ID: 839d334e07ea
Revises: 1356eb1f5a54
Create Date: 2026-01-09 16:32:48.112927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '839d334e07ea'
down_revision = '1356eb1f5a54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))

    # Create news table
    op.create_table('news',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('image_url', sa.String(), nullable=True),
        sa.Column('author', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.Column('published', sa.Boolean(), nullable=True),
        sa.Column('category', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news')
    
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
